version: '2'

services:
  apache:
      build: .
      ports:
          - 8080:80
      volumes:
          - .:/var/www
#      volumes_from:
#          - php
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    volumes:
       - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
